#!/bin/bash -eux

DIR=${1:-gcc-opt}
mkdir $DIR
cd $DIR

export CC=gcc
export CXX=g++

export CFLAGS='-O3 -DNDEBUG -march=native'
export CXXFLAGS=$CFLAGS
export LDFLAGS="-Wl,-rpath=$HOME/lib64 -Wl,-rpath=$HOME/lib"

cmake ../../llvm-project/llvm -G Ninja \
  -DCMAKE_BUILD_TYPE=Release \
  -DLLVM_ENABLE_PROJECTS="clang;cross-project-tests;lld" \
  -DLLVM_ENABLE_RUNTIMES="compiler-rt;libcxx;libcxxabi;libunwind" \
  -DCMAKE_C_FLAGS_RELEASE= \
  -DCMAKE_CXX_FLAGS_RELEASE= \
  -DCMAKE_INSTALL_PREFIX=$HOME/installs/llvm-gcc-$(date +'%Y-%m-%d') \
  -DCLANG_DEFAULT_CXX_STDLIB="libc++" \
  -DCLANG_DEFAULT_LINKER="lld" \
  -DCLANG_DEFAULT_OBJCOPY="llvm-objcopy" \
  -DCLANG_DEFAULT_RTLIB="compiler-rt" \
  -DCLANG_DEFAULT_UNWINDLIB="libunwind" \
  -DRUNTIMES_CMAKE_ARGS="-DLLVM_ENABLE_PER_TARGET_RUNTIME_DIR=OFF;-DLIBCXX_ENABLE_STATIC_ABI_LIBRARY=ON;-DLIBCXX_STATICALLY_LINK_ABI_IN_SHARED_LIBRARY=OFF;-DLIBCXX_STATICALLY_LINK_ABI_IN_STATIC_LIBRARY=ON;-DLIBCXX_USE_COMPILER_RT=ON;-DLIBCXX_HAS_ATOMIC_LIB=OFF;-DLIBCXXABI_ENABLE_STATIC_UNWINDER=ON;-DLIBCXXABI_STATICALLY_LINK_UNWINDER_IN_SHARED_LIBRARY=OFF;-DLIBCXXABI_STATICALLY_LINK_UNWINDER_IN_STATIC_LIBRARY=ON;-DLIBCXXABI_USE_COMPILER_RT=ON;-DLIBCXXABI_USE_LLVM_UNWINDER=ON;-DLIBUNWIND_USE_COMPILER_RT=ON;-DCOMPILER_RT_USE_BUILTINS_LIBRARY=ON;-DCOMPILER_RT_USE_LLVM_UNWINDER=ON;-DSANITIZER_CXX_ABI=libc++;-DSANITIZER_TEST_CXX=libc++" \
  -DBUILTINS_CMAKE_ARGS="-DCOMPILER_RT_DEFAULT_TARGET_ONLY=ON" \
  -DLLVM_CCACHE_BUILD=ON \
  -DLLVM_ENABLE_ASSERTIONS=OFF \
  -DLIBCXX_ENABLE_ASSERTIONS=OFF \
  -DLIBCXXABI_ENABLE_ASSERTIONS=OFF
